[project]
name = "cnnwtf"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "scikit-learn>=1.6.1",
    "tensorflow>=2.19.0",
    "tensorflow-datasets",
]
