[project]
name = "mindhacks"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "shap>=0.47.0",
    "tqdm>=4.67.1",
    "xgboost>=2.1.4",
]
