name: Deploy diamond price API

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jamesdeluk/diamond-price-fastapi:latest

      # - name: Deploy to server
      #   env:
      #     SSH_HOST: ${{ secrets.SSH_HOST }}
      #     SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      #     SSH_KEY: ${{ secrets.SSH_KEY }}
      #   run: |
      #     ssh -i $SSH_KEY $SSH_USERNAME@$SSH_HOST << 'EOF'
      #       docker pull username/repository:latest
      #       docker stop api_container || true
      #       docker rm api_container || true
      #       docker run -d --name api_container -p 8000:8000 username/repository:latest
      #     EOF